version: '3.1'
services:
  frontend-app:
    container_name: e_commerce_frontend
    image: e-commerce-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
