version: '3.1'
services:
  mongo-db:
    container_name: mongo_db
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

  backend-app:
    container_name: e-commerce_backend
    image: e-commerce-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo-db:27017
      DB_NAME: e-commerce
    depends_on:
      - mongo-db

volumes:
  mongodb_data:
